### ISSUE TITLE
invalid type: string "0", expected f64

### ISSUE THREAD

**Issue by secretshardul** [solana-labs/solana-program-library#1341]
Getting this error when checking token balance using CLI.

# Problematic commands
```sh
spl-token supply A8eYXMXcKctN9H6nwsFPDjsAvWq4hX8DywmaGsUPFRP4
spl-token balance AsmeE7T3MAVwsgytma4jtSbctYoexEooJj2a3my9ezc5
spl-token accounts
```

First and second commands throw this error
```
invalid type: string "0", expected f64
```

The third command throws
```sh
Account                                      Token                                        Balance
-------------------------------------------------------------------------------------------------
AsmeE7T3MAVwsgytma4jtSbctYoexEooJj2a3my9ezc5 Account parse failure: invalid type: string "0", expected f64
```

Error remains even after minting tokens.

Versions:
  - solana-cli 1.4.29 (src:4b0f6fd6; feat:3146620764)
  - spl-token-cli 2.0.6

Environment: Intel MacOS Catalina
Terminal: zsh

**Comment by ysavchenko** [comment]
Same thing here. Also when attempting to reinstall spl-token-cli I get build errors.

`cargo install spl-token-cli`

```
error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:435:41
    |
435 |     let ui_amount = ui_amount.unwrap_or(sender_balance);
    |                                         ^^^^^^^^^^^^^^ expected `f64`, found struct `std::string::String`

error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:441:20
    |
441 |     if ui_amount > sender_balance {
    |                    ^^^^^^^^^^^^^^ expected `f64`, found struct `std::string::String`

error[E0277]: can't compare `std::string::String` with `{float}`
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:730:79
    |
730 |         if !source_account.is_native && source_account.token_amount.ui_amount > 0.0 {
    |                                                                               ^ no implementation for `std::string::String < {float}` and `std::string::String > {float}`
    |
    = help: the trait `PartialOrd<{float}>` is not implemented for `std::string::String`

error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:880:33
    |
880 | ...                   ui_token_account.token_amount.ui_amount,
    |error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:435:41
    |
435 |     let ui_amount = ui_amount.unwrap_or(sender_balance);
    |                                         ^^^^^^^^^^^^^^ expected `f64`, found struct `std::string::String`

error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:441:20
    |
441 |     if ui_amount > sender_balance {
    |                    ^^^^^^^^^^^^^^ expected `f64`, found struct `std::string::String`

error[E0277]: can't compare `std::string::String` with `{float}`
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:730:79
    |
730 |         if !source_account.is_native && source_account.token_amount.ui_amount > 0.0 {
    |                                                                               ^ no implementation for `std::string::String < {float}` and `std::string::String > {float}`
    |
    = help: the trait `PartialOrd<{float}>` is not implemented for `std::string::String`

error[E0308]: mismatched types
   --> /Users/ysavchenko/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-token-cli-2.0.6/src/main.rs:880:33
    |
880 | ...                   ui_token_account.token_amount.ui_amount,
    |
```

**Comment by ryoqun** [comment]
@secretshardul @ysavchenko Thanks for quick reporting. it seems that we released v1.5.9 a bit before.

**Comment by ryoqun** [comment]
it seems that this caused by https://github.com/solana-labs/solana/pull/15447

**Comment by secretshardul** [comment]
Is there any temporary fix? I downgraded to Solana `1.3.22`, but then it showed that `spl-token-cli` is not installed. Tried reinstalling it but now it shows the error posted by @ysavchenko

**Comment by ryoqun** [comment]
we're now fixing this: https://github.com/solana-labs/solana/pull/15535

**Comment by ryoqun** [comment]
@secretshardul @ysavchenko Hi thanks for quick reporting; we believe this is now solved in full. Please report if you're still seeing any problems. :)
