### ISSUE TITLE
Stake pool SDK throws "seed.toBuffer" is not a function when loading the stakePoolInfo in 0.7.0 and later

### ISSUE THREAD

**Issue by rockooor** [solana-labs/solana-program-library#6269]
Hi,

I noticed the stake pool SDK throws this error:

```
TypeError: seed.toBuffer is not a function
    at findTransientStakeProgramAddress (index.browser.esm.js:103:14)
    at eval (index.browser.esm.js:1969:52)
    at async Promise.all (dapp/index 0)
    at async Module.stakePoolInfo (index.browser.esm.js:1967:27)
    at async Object.eval [as queryFn] (useStakepool.ts:13:1)
```

when I run this snippet of code

```
const info = await stakePoolInfo(
            connection,
            new PublicKey('stk9ApL5HeVAwPLr3TLhDXdZS8ptVu7zp6ov8HFDuMi'),
        );

        return info;
```

(it can't be more minimal). This stake pool key is the one from solblaze.

It works on v0.6.5, but on v0.7.0 and v1.0.0 it's broken.

When creating a breakpoint on the `findTransientStakeProgramAddress`, I get the following info:

![telegram-cloud-photo-size-4-5951632673258716234-x](https://github.com/solana-labs/solana-program-library/assets/121937361/ce056957-5ca9-4da1-97ff-069d46f3158f)

So it seems the cogent validator's seed is `0`, and the `toBuffer` function fails because it's not a PublicKey (obviously).

**Comment by joncinque** [comment]
Thanks for reporting the issue! This was fixed in #6226, so I've tagged and released 1.0.1 with the fix in #6276
